#!/usr/bin/env bash

workspaces() {
	unset -v \
	o1 o2 o3 o4 o5 o6 o7 o8 o9 \
	f1 f2 f3 f4 f5 f6 f7 f8 f9 \
	ic_1 ic_2 ic_3 ic_4 ic_5 ic_6 ic_7 ic_8 ic_9

	ows="$(hyprctl workspaces -j | jq '.[] | del(select(.id == -99)) | .id')"

	for num in $ows; do
		export o"$num"="$num"
	done

	num="$(hyprctl monitors -j | jq '.[] | select(.id == 0).activeWorkspace.id')"
	export f"$num"="$num"

	ic_1=""
	ic_2=""
	ic_3=""
	ic_4=""
	ic_5=""
	ic_6=""
	ic_7=""
	ic_8=""
	ic_9=""

	if [ "$f1" ]; then
	    ic_1=""
	elif [ "$f2" ]; then
	    ic_2=""
	elif [ "$f3" ]; then
	    ic_3=""
	elif [ "$f4" ]; then
	    ic_4=""
	elif [ "$f5" ]; then
	    ic_5=""
	elif [ "$f6" ]; then
	    ic_6=""
	elif [ "$f7" ]; then
	    ic_7=""
	elif [ "$f8" ]; then
	    ic_8=""
	elif [ "$f9" ]; then
	    ic_9=""
	fi

	echo	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" \
			(button :onclick \"hyprctl dispatch workspace 1\" :class \"$un$o1$f1\" \"$ic_1\") \
			(button :onclick \"hyprctl dispatch workspace 2\" :class \"$un$o2$f2\" \"$ic_2\") \
			(button :onclick \"hyprctl dispatch workspace 3\" :class \"$un$o3$f3\" \"$ic_3\") \
			(button :onclick \"hyprctl dispatch workspace 4\" :class \"$un$o4$f4\" \"$ic_4\") \
			(button :onclick \"hyprctl dispatch workspace 5\" :class \"$un$o5$f5\" \"$ic_5\") \
			(button :onclick \"hyprctl dispatch workspace 6\" :class \"$un$o6$f6\" \"$ic_6\") \
			(button :onclick \"hyprctl dispatch workspace 7\" :class \"$un$o7$f7\" \"$ic_7\") \
			(button :onclick \"hyprctl dispatch workspace 8\" :class \"$un$o8$f8\" \"$ic_8\") \
			(button :onclick \"hyprctl dispatch workspace 9\" :class \"$un$o9$f9\" \"$ic_9\"))"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
	workspaces "$event"
done
