# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1810a37f-a7b2-4a2f-a93f-38b506061441";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c004511c-215f-4f85-b2a7-951ae9bfa249".device = "/dev/disk/by-uuid/c004511c-215f-4f85-b2a7-951ae9bfa249";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/b5834e8f-6808-4ce0-9f8c-6b5104469941";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A4C-E558";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { 
        device = "/dev/disk/by-uuid/8f578107-4be7-4ef5-b690-4c559c4bf040"; 
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
