# .sops.yaml
#
# Add servers with:
#   ssh-keyscan -t ed25519 [hostname] | nix run nixpkgs#ssh-to-age.
#
# Edit secrets with:
#   nix run nixpkgs#sops -- ~/nix/nixos/[host]/secrets/secrets.yml
#
# Use sops updatekeys command to re-key corresponding files:
#   nix run nixpkgs#sops -- updatekeys [filename].

keys:
  - &admin_totaltax F86DD3C43118758BA5A3D3A9718CE018D826D164

  - &host_laptop age12v98gyllwrul8ckunvyqqj4zmftltjt7ed74s6msmvdp3fcgn5vq90fzyh
  - &host_remote age1glckwtavpgnv8cauzh9jqryxs367lm4tjf8fruvewl6exajh65aq4cqk8u

creation_rules:
  - path_regex: nixos/laptop/secrets/[^/]+\.yml$
    key_groups:
      - pgp:
        - *admin_totaltax
        age:
        - *host_laptop

