{
  pkgs,
  config,
  user,
  host,
  inputs,
  system,
  lib,
  ...
}:

let
  backgrounds-dir = pkgs.stdenvNoCC.mkDerivation {
    name = "background-dir";
    src = ./backgrounds;
    dontBuild = true;
    installPhase = ''
      mkdir -p $out/share/
      cp -r ${./backgrounds/.} $out/share/backgrounds/
    '';
  };

  # TODO: Make this better
  backgrounds =
    let
      script = ''
        #!${pkgs.python314}/bin/python3

        import os
        import subprocess
        import time
        import random
        from pathlib import Path

        os.environ['AWWW_TRANSITION_FPS'] = '60'
        os.environ['AWWW_TRANSITION_STEP'] = '2'
        os.environ['AWWW_TRANSITION'] = 'center'
        interval = 60

        def set_wallpaper_image_awww(path, output=None):
            cmd = [f'${pkgs.awww}/bin/awww', 'img']
            if output:
                cmd += ['-o', output]
            cmd.append(path)
            subprocess.run(cmd)

      ''
      + (
        if host == "laptop" then
          ''
            time.sleep(2)
            subprocess.Popen([f'${pkgs.awww}/bin/awww-daemon'], close_fds=True)
            time.sleep(2)
            wallpaper_dir = Path(f'${backgrounds-dir}/share/backgrounds/laptop')
            image_files = list(wallpaper_dir.glob('*.jpg'))

            while True:
                shuffled_files = random.sample(image_files, len(image_files))
                for path in shuffled_files:
                    print(f"switch: {path}")
                    set_wallpaper_image_awww(path)
                    time.sleep(interval)
          ''
        else if host == "desktop" then
          ''
            # TODO: Enable when swww works on 2nd monitor
            subprocess.Popen([f'${pkgs.hyprpaper}/bin/hyprpaper'], close_fds=True)
            # set_wallpaper_image_swww(f'${backgrounds-dir}/share/backgrounds/desktop/ultrawide.png', 'DP-1')
            # set_wallpaper_image_swww(f'${backgrounds-dir}/share/backgrounds/desktop/2nd.jpg', 'HDMI-A-1')
          ''
        else
          ''
            print("No background for ${host}")
            exit(1)
          ''
      );
    in
    pkgs.writeScriptBin "backgrounds" script;

  audioSwitcher = pkgs.writeScriptBin "audioSwitcher" ''
    #!${pkgs.python314}/bin/python
    import sys
    import subprocess
    import re

    """
    WirePlumber switcher using node.description for clean Rofi menus.
    """

    def get_nodes(target_class):
        proc = subprocess.run(["${pkgs.wireplumber}/bin/wpctl", "status"], capture_output=True, text=True)
        potential_ids = re.findall(r"(\*?)\s+(\d+)\.", proc.stdout)
        valid_nodes = []
        seen_ids = set()

        for is_default, node_id in potential_ids:
            if node_id in seen_ids:
                continue
            seen_ids.add(node_id)
            inspect = subprocess.run(["${pkgs.wireplumber}/bin/wpctl", "inspect", node_id], capture_output=True, text=True)
            if f'media.class = "{target_class}"' in inspect.stdout:
                desc_match = re.search(r'node.description = "(.*)"', inspect.stdout)
                friendly_name = desc_match.group(1) if desc_match else f"Unknown Device ({node_id})"
                display = f"{node_id}. {friendly_name}"
                if "*" in is_default:
                    display = f"<b>{display} *</b>"
                valid_nodes.append(display)

        return valid_nodes

    def main():
        if len(sys.argv) != 2:
            print("Usage: audioSwitcher <Sinks|Sources>")
            sys.exit(1)

        category = sys.argv[1]
        target_class = "Audio/Sink" if category == "Sinks" else "Audio/Source"
        nodes = get_nodes(target_class)

        if not nodes:
            print(f"No valid {category} found.")
            sys.exit(1)

        rofi = subprocess.run(
            ["${pkgs.rofi}/bin/rofi", "-dmenu", "-markup-rows", "-p", f"Select {category[:-1]}"],
            input="\n".join(nodes),
            text=True,
            capture_output=True
        )

        if rofi.returncode == 0 and rofi.stdout.strip():
            clean_selection = re.sub(r"<[^>]*>", "", rofi.stdout.strip())
            node_id = clean_selection.split(".")[0].strip()
            subprocess.run(["${pkgs.wireplumber}/bin/wpctl", "set-default", node_id])

    if __name__ == "__main__":
        main()
  '';

  screen-rec = pkgs.writeScriptBin "screen-rec" ''
    if pgrep -x "wl-screenrec" > /dev/null; then
      killall -s 2 wl-screenrec
      exit 0
    fi

    FILE="$XDG_SCREENREC_DIR/$(date +'screencast_%Y%m%d%H%M%S.mp4')"

    wl-screenrec -g "$(slurp && dunstify "Starting screencast" --timeout=1000)" --filename $FILE &&
    ffmpeg -i $FILE -ss 00:00:00 -vframes 1 /tmp/screenrec_thumbnail.png -y &&
    printf -v out "`dunstify "Recording saved to $FILE" \
        --icon "/tmp/screenrec_thumbnail.png" \
        --action="default,Open"`"
  '';

  hyprlandLua = ''
    -- Generated by hyprland.nix — do not hand edit the generated file,
    -- edit this Nix module instead.

    local host = "${host}"
    local mod = "SUPER"

    -- animations -----------------------------------------------------------
    hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
    hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "myBezier" })
    hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
    hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
    hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default" })

    -- monitors ---------------------------------------------------------------
    if host == "desktop" then
      hl.monitor({
        output = "DP-1",
        mode = "3440x1440@165",
        position = "0x0",
        scale = "1",
        vrr = 3,
        cm = "auto",
      })
      hl.monitor({
        output = "HDMI-A-1",
        mode = "preferred",
        position = "-1440x-600",
        scale = "1",
        transform = 3,
      })
    elseif host == "laptop" then
      hl.monitor({ output = "eDP-1", mode = "2880x1800@120", position = "0x0", scale = 1.25 })
      -- Second eDP entry kept for parity with the previous hyprland.conf;
      -- unclear why the laptop reports two eDP outputs.
      hl.monitor({ output = "eDP-2", mode = "2880x1800@120", position = "0x0", scale = 1.25 })
      hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
    end

    -- env vars -----------------------------------------------------------
    hl.env("XCURSOR_SIZE", "${toString config.cursor.size}")
    hl.env("XCURSOR_THEME", "${config.cursor.name}")
    hl.env("HYPRCURSOR_SIZE", "${toString config.cursor.size}")
    hl.env("HYPRCURSOR_THEME", "${config.cursor.name}")

    if host == "laptop" then
      hl.env("AQ_DRM_DEVICES", "/dev/dri/amd-igpu")
    elseif host == "desktop" then
      hl.env("LIBVA_DRIVER_NAME", "nvidia")
      hl.env("XDG_SESSION_TYPE", "nvidia")
      hl.env("GDM_BACKEND", "nvidia-drm")
      hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
    end

    -- gestures -----------------------------------------------------------
    hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

    -- core config ----------------------------------------------------------
    hl.config({
      animations = { enabled = true },
      cursor = {
        no_hardware_cursors = (host == "desktop"),
      },
      debug = { disable_logs = false },
      decoration = {
        shadow = {
          color = "rgb(${config.colorScheme.palette.base0D})",
          color_inactive = "rgb(${config.colorScheme.palette.base03})",
          enabled = false,
          range = 5,
          render_power = 3,
        },
        rounding = 5,
      },
      dwindle = { preserve_split = true },
      general = {
        border_size = 2,
        col = {
          active_border = "rgb(${config.colorScheme.palette.base0D})",
          inactive_border = "rgb(${config.colorScheme.palette.base03})",
        },
        gaps_in = 2,
        gaps_out = 4,
        layout = "dwindle",
      },
      input = {
        touchpad = {
          clickfinger_behavior = true,
          disable_while_typing = false,
          natural_scroll = false,
        },
        accel_profile = "flat",
        follow_mouse = 1,
        kb_layout = "us",
        sensitivity = (host == "laptop") and 0.5 or 0,
      },
      misc = {
        disable_hyprland_logo = true,
        enable_anr_dialog = false,
        middle_click_paste = false,
      },
      xwayland = { force_zero_scaling = true },
    })


    -- keybinds -----------------------------------------------------------
    hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("alacritty"))
    hl.bind(mod .. " + E", hl.dsp.exec_cmd("firefox-devedition -P dev-edition-default"))
    hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("firefox-devedition -P School"))
    hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
    hl.bind(mod .. " + Q", hl.dsp.window.close())
    hl.bind(mod .. " + G", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mod .. " + R", hl.dsp.exec_cmd("rofi -show drun"))
    hl.bind(mod .. " + P", hl.dsp.window.pseudo())
    hl.bind(mod .. " + a", hl.dsp.focus({ direction = "left" }))
    hl.bind(mod .. " + d", hl.dsp.focus({ direction = "right" }))
    hl.bind(mod .. " + w", hl.dsp.focus({ direction = "up" }))
    hl.bind(mod .. " + s", hl.dsp.focus({ direction = "down" }))
    hl.bind(mod .. " + SHIFT + a", hl.dsp.window.move({ direction = "l" }))
    hl.bind(mod .. " + SHIFT + d", hl.dsp.window.move({ direction = "r" }))
    hl.bind(mod .. " + SHIFT + w", hl.dsp.window.move({ direction = "u" }))
    hl.bind(mod .. " + SHIFT + s", hl.dsp.window.move({ direction = "d" }))


    hl.bind(mod .. " + L", hl.dsp.exec_cmd("hyprlock"))
    hl.bind("CTRL + SHIFT + Print", hl.dsp.exec_cmd("grimblast --notify copysave screen $XDG_SCREENSHOTS_DIR/$(date '+%b.%d.%Y-%H:%M:%S')-screenshot.png"))
    hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast --notify copysave area $XDG_SCREENSHOTS_DIR/$(date '+%b.%d.%Y-%H:%M:%S')-screenshot.png"))
    hl.bind("ALT + Print", hl.dsp.exec_cmd("${screen-rec}/bin/screen-rec"))
    hl.bind(mod .. " + V", hl.dsp.exec_cmd("rofi-copyq"))
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
    hl.bind(mod .. " + SHIFT + O", hl.dsp.exec_cmd("${audioSwitcher}/bin/audioSwitcher Sinks"))
    hl.bind(mod .. " + SHIFT + I", hl.dsp.exec_cmd("${audioSwitcher}/bin/audioSwitcher Sources"))
    hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("amixer set Master 5%+"), { repeating = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("amixer set Master 5%-"), { repeating = true })
    hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { repeating = true })
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play"), { repeating = true })

    hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
    hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

    if host == "laptop" then
      hl.bind("CTRL + SHIFT + code:72", hl.dsp.exec_cmd("grimblast --notify copysave screen $XDG_SCREENSHOTS_DIR/$(date '+%b.%d.%Y-%H:%M:%S')-screenshot.png"))
      hl.bind("SHIFT + code:72", hl.dsp.exec_cmd("grimblast --notify copysave area $XDG_SCREENSHOTS_DIR/$(date '+%b.%d.%Y-%H:%M:%S')-screenshot.png"))
      hl.bind("ALT + code:72", hl.dsp.exec_cmd("${screen-rec}/bin/screen-rec"))
      hl.bind(mod .. " + RIGHT", hl.dsp.exec_cmd("playerctl next"))
      hl.bind(mod .. " + LEFT", hl.dsp.exec_cmd("playerctl previous"))

      hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -m -d $(brightnessctl -l | grep amdgpu_bl | awk '{print $2}' | sed \"s/'//g\") s 5%-"), { repeating = true })
      hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -m -d $(brightnessctl -l | grep amdgpu_bl | awk '{print $2}' | sed \"s/'//g\") s 5%+"), { repeating = true })
      hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("brightnessctl -m --device='asus::kbd_backlight' s 1+"), { repeating = true })
      hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl -m --device='asus::kbd_backlight' s 1-"), { repeating = true })

      hl.bind("switch:[Lid Switch]:on", hl.dsp.exec_cmd("hyprlock"))
    end

    -- start-up -------------------------------------------------------------
    hl.on("hyprland.start", function()
      -- hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
      hl.exec_cmd("${backgrounds}/bin/backgrounds")
      hl.exec_cmd("${pkgs.copyq}/bin/copyq")
      hl.exec_cmd("hyprctl setcursor ${config.cursor.name} ${toString config.cursor.size}")

      if host == "laptop" then
        hl.exec_cmd("${pkgs.eww}/bin/eww open laptopMain")
      elseif host == "desktop" then
        hl.exec_cmd("${pkgs.eww}/bin/eww open-many main0 main1")
        hl.exec_cmd("xrandr --output DP-1 --primary")
        hl.exec_cmd("${pkgs.openrgb}/bin/openrgb -p ~/.config/OpenRGB/White.orp") -- TODO: nixify this path
      end
    end)
  '';
in
{
  home.packages = with pkgs; [
    wlr-randr
    backgrounds
    audioSwitcher
    hyprland-activewindow
  ];

  xdg.portal.extraPortals = with pkgs; [
    xdg-desktop-portal-gtk
  ];

  # TODO: remove once swww issue is fixed
  xdg.configFile."hypr/hyprpaper.conf".text = ''
    wallpaper {
      monitor = DP-1
      path = ${backgrounds-dir}/share/backgrounds/desktop/ultrawide.png
    }
    wallpaper {
      monitor = HDMI-A-1
      path = ${backgrounds-dir}/share/backgrounds/desktop/2nd.jpg
    }
  '';

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    systemd.enable = false;

    package = lib.mkDefault inputs.hyprland.packages.${system}.hyprland;

    configType = "lua";

    plugins = [ ];

    extraLuaFiles = {
      "hyprsplit/init" = {
        autoLoad = false;
        content = builtins.readFile "${
          inputs.hyprsplit.packages.${system}.hyprsplitlua
        }/share/hyprsplit/init.lua";
      };
      "hyprload" = {
        autoLoad = true;
        content = ''
          local hs = require("hyprsplit")
          local mod = "SUPER"

          hs.config({ num_workspaces = 9 })

          for i = 1, 9 do
            hl.bind(mod .. " + " .. i, hs.dsp.focus({ workspace = i }))
            hl.bind(mod .. " + SHIFT + " .. i, hs.dsp.window.move({ workspace = i, follow = false }))
          end
          -- workspace 10 kept reachable the same way the old config did,
          -- via shift+0, with no plain mod+0 bind
          hl.bind(mod .. " + SHIFT + 0", hs.dsp.window.move({ workspace = 10, follow = false }))

          -- Available but not wired up — handy if monitors get
          -- unplugged/replugged or you want workspace-swap binds later:
          -- hl.bind(mod .. " + G", hs.dsp.grab_rogue_windows())
          -- hl.bind(mod .. " + SHIFT + G", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "+1" }))
        '';
      };
    };

    settings = { };

    extraConfig = hyprlandLua;
  };
}
