{
  tomorrow-night-dark = {
    slug = "tomorrow-dark";
    name = "Tomorrow Night Dark";
    author = "jntesteves (modified by TotalTaxAmount)";
    colors = {
      base00 = "000000";
      base01 = "282a2e";
      base02 = "373b41"; 
      base03 = "969896"; 
      base04 = "b4b7b4"; 
      base05 = "c5c8c6"; 
      base06 = "eaeaea";
      base07 = "ffffff"; 
      base08 = "d54e53";
      base09 = "e78c45"; 
      base0A = "e7c547"; 
      base0B = "b9ca4a";
      base0C = "70c0b1";
      base0D = "7aa6da"; 
      base0E = "c397d8"; 
      base0F = "a3685a";
    };
  };
  oxocarbon = {
    slug = "oxocarbon";
    name = "Oxocarbon Dark";
    author = "shaunsingh/IBM";
    colors = {
      base00 = "161616";
      base01 = "262626"; 
      base02 = "393939"; 
      base03 = "525252"; 
      base04 = "dde1e6"; 
      base05 = "f2f4f8"; 
      base06 = "ffffff"; 
      base07 = "08bdba";
      base08 = "3ddbd9"; 
      base09 = "78a9ff"; 
      base0A = "ee5396"; 
      base0B = "33b1ff"; 
      base0C = "ff7eb6"; 
      base0D = "42be65"; 
      base0E = "be95ff"; 
      base0F = "82cfff";
    };
  };

  autogenerated = {
    name = "Auto generated theme";
    slug = "auto-generated";
    author = "Auto Base16 Theme (https://github.com/makuto/auto-base16-theme/)";

    colors = {
      base00 = "030625";
      base01 = "361532";
      base02 = "121853";
      base03 = "9b2882";
      base04 = "e217e2";
      base05 = "d33673";
      base06 = "20225f";
      base07 = "491f71";

      base08 = "ff786d";
      base09 = "d84991";
      base0A = "e938c8";
      base0B = "e938c8";
      base0C = "e938c8";
      base0D = "d33673";
      base0E = "d84991";
      base0F = "d84991";
    };
  };
}