name: Build Flake for All Hosts
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [laptop, desktop, remote]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1

      - name: Build flake
        run: nix build .#${{ matrix.host }} --extra-experimental-features "nix-command flakes"
